### PR TITLE
Update addon.xml

### PR DESCRIPTION
**Pull request by pecinko**
Suggestion

### CODE REVIEW

**Comment by queeup** [comment]
Thanks. What can we use instead Nextup? I don't think it means too much. Also Maybe mention one episode from each tv-show?

**Comment by pecinko** [comment]
Unwatched episodes?

**Comment by queeup** [comment]
Next unwatched episode per TV-Show or for each TV-Show? My English not enough to explain what this add-on doing :)

**Comment by pecinko** [comment]
First unwatched episode per tv show, I guess.

**Comment by queeup** [comment]
OK. It looks good. Could you make changes on your for and commit it. It will appear here and I can pull.

**Comment by queeup** [comment]
Thank you.

**Pull request merged**
